
/**************************************************************
 *	
 *	accept, 8 bit, 11025Hz,
 *	1 channel, 9606 bytes/channel
 *	Total Size: 1 * 9606 + 4 (header) = 9650 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/marianamatias/CS2261/Milestones/M4/M04_v3/accept.wav
 *	Time-stamp: Tue Nov 27 21:26:04 2018
 *	
 **************************************************************/

#ifndef __ACCEPTH__
#define __ACCEPTH__

#define ACCEPTFREQ 11025
#define ACCEPTLEN 9606

extern const unsigned char accept[9606];

#endif /* __ACCEPTH__ */
