
/**************************************************************
 *	
 *	collideSound, 8 bit, 11025Hz,
 *	1 channel, 55125 bytes/channel
 *	Total Size: 1 * 55125 + 4 (header) = 55169 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/marianamatias/CS2261/Milestones/M4/M04_v2/collideSound.wav
 *	Time-stamp: Tue Nov 27 13:39:46 2018
 *	
 **************************************************************/

#ifndef __COLLIDESOUNDH__
#define __COLLIDESOUNDH__

#define COLLIDESOUNDFREQ 11025
#define COLLIDESOUNDLEN 55125

extern const unsigned char collideSound[55125];

#endif /* __COLLIDESOUNDH__ */
