
/**************************************************************
 *	
 *	gameSong, 8 bit, 11025Hz,
 *	1 channel, 255301 bytes/channel
 *	Total Size: 1 * 255301 + 4 (header) = 255345 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/marianamatias/CS2261/Milestones/M4/M04_v2/gameSong.wav
 *	Time-stamp: Tue Nov 27 14:35:30 2018
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 255301

extern const unsigned char gameSong[255301];

#endif /* __GAMESONGH__ */
