
/**************************************************************
 *	
 *	loseSound, 8 bit, 11025Hz,
 *	1 channel, 45764 bytes/channel
 *	Total Size: 1 * 45764 + 4 (header) = 45808 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/marianamatias/CS2261/Milestones/Final/final_v2/loseSound.wav
 *	Time-stamp: Sat Dec 01 15:11:16 2018
 *	
 **************************************************************/

#ifndef __LOSESOUNDH__
#define __LOSESOUNDH__

#define LOSESOUNDFREQ 11025
#define LOSESOUNDLEN 45764

extern const unsigned char loseSound[45764];

#endif /* __LOSESOUNDH__ */
