
/**************************************************************
 *	
 *	magic, 8 bit, 11025Hz,
 *	1 channel, 7698 bytes/channel
 *	Total Size: 1 * 7698 + 4 (header) = 7742 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/marianamatias/CS2261/Milestones/Final/final_v2/magic.wav
 *	Time-stamp: Sat Dec 01 15:30:20 2018
 *	
 **************************************************************/

#ifndef __MAGICH__
#define __MAGICH__

#define MAGICFREQ 11025
#define MAGICLEN 7698

extern const unsigned char magic[7698];

#endif /* __MAGICH__ */
