
/**************************************************************
 *	
 *	menuSong, 8 bit, 11025Hz,
 *	1 channel, 132068 bytes/channel
 *	Total Size: 1 * 132068 + 4 (header) = 132112 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/marianamatias/CS2261/Milestones/M4/M04_v2/menuSong.wav
 *	Time-stamp: Tue Nov 27 14:36:20 2018
 *	
 **************************************************************/

#ifndef __MENUSONGH__
#define __MENUSONGH__

#define MENUSONGFREQ 11025
#define MENUSONGLEN 132068

extern const unsigned char menuSong[132068];

#endif /* __MENUSONGH__ */
