
/**************************************************************
 *	
 *	winSound, 8 bit, 11025Hz,
 *	1 channel, 18202 bytes/channel
 *	Total Size: 1 * 18202 + 4 (header) = 18246 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/marianamatias/CS2261/Milestones/Final/final_v2/winSound.wav
 *	Time-stamp: Sat Dec 01 15:12:25 2018
 *	
 **************************************************************/

#ifndef __WINSOUNDH__
#define __WINSOUNDH__

#define WINSOUNDFREQ 11025
#define WINSOUNDLEN 18202

extern const unsigned char winSound[18202];

#endif /* __WINSOUNDH__ */
